Traceback (most recent call last):
  File "train_gg.py", line 2, in <module>
    import pandas as pd
  File "/usr/lib64/python2.6/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy_compat import *
  File "/usr/lib64/python2.6/site-packages/pandas/compat/__init__.py", line 298, in <module>
    from collections import OrderedDict, Counter
ImportError: cannot import name Counter
i 1000 j 12
0.401067840351
i 1000 j 13
0.402081107458
i 1000 j 14
0.401263824866
i 1000 j 15
0.399498298163
i 1000 j 16
0.397019027506
i 1000 j 17
0.39414981643
i 1000 j 18
0.39096808447
i 1000 j 19
0.387803727756
i 3000 j 12
0.401150753351
i 3000 j 13
0.4021125451
i 3000 j 14
0.401334607488
i 3000 j 15
0.399594313937
i 3000 j 16
0.397143043912
i 3000 j 17
0.39426018283
i 3000 j 18
0.391164640145
i 3000 j 19
0.388012643377
i 5000 j 12
0.401170894229
i 5000 j 13
0.402129862871
i 5000 j 14
0.40135035591
i 5000 j 15
0.399629712533
i 5000 j 16
0.397163447872
i 5000 j 17
0.394308726137
i 5000 j 18
0.391206329895
i 5000 j 19
0.388079737397
i 7000 j 12
0.401175731336
i 7000 j 13
0.402128469227
i 7000 j 14
0.40136385735
i 7000 j 15
0.399630837043
i 7000 j 16
0.397175052448
i 7000 j 17
0.394293581801
i 7000 j 18
0.391200957717
i 7000 j 19
0.388051752828
i 9000 j 12
0.401194530131
i 9000 j 13
